# Generated by Django 5.0.6 on 2024-06-05 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sulg',
            new_name='slug',
        ),
    ]
